django_movie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]
if settings.DEBUG:
    print(settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('', MoviesList.as_view(), name='movies_list_url'),
    path('filter/', FilteradMoviesList.as_view(), name='filter_url'),
    path('review/<int:pk>/', AddRewiew.as_view(), name='add_review'),
    path('actor/<slug:slug>/', ActorDetail.as_view(), name='actor_detail_url'),
    path('<slug:slug>/', MovieDetails.as_view(), name='movie_detail_url'),

]

movies/models.py
from django.db import models
from datetime import date

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField('Category', max_length=40)
    description = models.TextField('Description', max_length=150, blank=True)
    url = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Actor(models.Model):
    name = models.CharField(max_length=50)
    age = models.PositiveSmallIntegerField(default=0)
    description = models.TextField('Description', max_length=150, blank=True)
    image = models.ImageField('Image', upload_to='actors/')
    url = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Actors and Directors'
        verbose_name_plural = 'Actors and Directors'

    def get_absolute_url(self):
        return reverse('actor_detail_url', kwargs={'slug': self.url})


class Genre(models.Model):
    name = models.CharField('Category', max_length=40)
    description = models.TextField('Description', max_length=150, blank=True)
    url = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=100)
    tagline = models.CharField(max_length=500, default='')
    description = models.TextField(max_length=150, blank=True)
    poster = models.ImageField('Logo', upload_to='movies/')
    year = models.PositiveSmallIntegerField(default=int(str(date.today())[:4]))
    country = models.CharField(max_length=30, default='')
    directors = models.ManyToManyField(Actor, verbose_name='director', related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='actor', related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='genre', related_name='film_genre')
    world_premier = models.DateField('Premier', default=date.today)
    budget = models.PositiveSmallIntegerField(default=0, help_text='Set in $')
    fees_in_usa = models.PositiveSmallIntegerField(default=0, help_text='Set in $')
    fees_in_world = models.PositiveSmallIntegerField(default=0, help_text='Set in $')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    def get_absolute_url(self):
        return reverse('movie_detail_url', kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Movie'
        verbose_name_plural = 'Movies'


class MovieShots(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=150, blank=True)
    image = models.ImageField(upload_to='movie_shots/')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Movie shot'
        verbose_name_plural = 'Movie shots'


class RatingStar(models.Model):
    value = models.SmallIntegerField(default=0)

    def __str__(self):
        return str(self.value)

    class Meta:
        verbose_name = 'Rating star'
        verbose_name_plural = 'Rating stars'


class Rating(models.Model):
    ip = models.CharField('IP address', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, )

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = 'Rating'
        verbose_name_plural = 'Ratings'


class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=50)
    text = models.TextField(max_length=3000)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

movies/forms.py
from django import forms
from .models import Reviews


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')

movies/views.py
from django.db.models import Q
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Movie, Actor,Genre
from .forms import ReviewForm

class GenreYear():
    def get_genre(self):
        return Genre.objects.all()
    def get_year(self):
        return Movie.objects.filter(draft=False).values('year').distinct()

class MoviesList(GenreYear,ListView):
    model = Movie
    template_name = 'movies/movies.html'
    context_object_name = 'content'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        movies = self.model.objects.filter(draft=False)
        context['movies'] = movies
        return context

class MovieDetails(GenreYear, DetailView):
    model = Movie
    slug_field = 'url'
    template_name = 'movies/moviesingle.html'
    context_object_name = 'movie'

class ActorDetail(GenreYear,DetailView):
    model = Actor
    slug_field = 'url'
    template_name = 'movies/actor.html'
    context_object_name = 'actor'

class AddRewiew(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False) #Зберігає усі поля із форми, але в Бд не пише
            if request.POST.get('parent',None):
                form.parent_id = int(request.POST.get('parent'))
            form.movie = movie
            form.save()

        return redirect(movie.get_absolute_url())

class FilteradMoviesList(GenreYear,ListView):
    template_name = 'movies/movies.html'
    context_object_name = 'content'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        movies = Movie.objects.filter(Q(draft=False) & Q(year__in=self.request.GET.getlist('year'))|Q(genres__in=self.request.GET.getlist('genre')))
        context['movies'] = movies
        return context

    # def get_queryset(self):
    #     queryset = Movie.objects.filter(Q(year__in=self.request.GET.getlist('year'))|Q(genres__in=self.request.GET.getlist('genre')))
    #     print(queryset)
    #     return queryset

movies/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <!-- //Meta tag Keywords -->
    <title>Clack Website Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.css'%}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static '/css/style.css'%}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static '/css/font-awesome.css'%}" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">
    <!-- //Fonts -->
</head>
<body>
<div id="page" class="page"><!-- mian-content -->
    {%block logo%}

        {%endblock logo%}

        <!-- header -->
        {%include 'include/header.html'%}
        <!-- //header -->
    </div>
    <ol class="breadcrumb editContent">
        <li class="breadcrumb-item">
            <a href="index.html" class="editContent">Home</a>
        </li>
        <li class="breadcrumb-item active editContent">Single Page</li>
    </ol>
</div>
<!---->
<!-- banner -->
<section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
    <div class="container-fluid py-md-3">
        <div class="row">
            <div class="side-bar col-lg-3">
                {%include 'include/sidebar.html'%}
            </div>
            {%block content%}
            {%endblock content%}
            {%include 'include/footer.html'%}
        </div>

    </div>
</section>
</body>
</html>

movies/templates/include/footer.html
<footer class="editContent">
    <div class="container">
        <div class="row footer-top">
            <div class="col-lg-4 footer-grid_section_w3layouts">
                <h2 class="logo-2 mb-lg-4 mb-3">
                    <a href="index.html" class="editContent">
                                <span class="fa" aria-hidden="true">
                                    Django School
                                </span>
                    </a>
                </h2>
                <p class="editContent">
                    Канал для программистов и людей, которые хотят развиваться в сфере IT.
                    Видео уроки по python 3, Django 2, Django 3, JavaScript, Vue.js, HTML, CSS
                    и многое другое.
                </p>
                <h4 class="sub-con-fo ad-info my-4 editContent">Catch on Social</h4>
                <ul class="w3layouts_social_list media-soc list-unstyled">
                    <li>
                        <a href="#" class="w3pvt_facebook editContent">
                            <span class="fa fa-facebook-f"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_twitter editContent">
                            <span class="fa fa-twitter"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_dribble editContent">
                            <span class="fa fa-dribbble"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_google editContent">
                            <span class="fa fa-google-plus"></span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-8 footer-right">
                <div class="w3layouts-news-letter">
                    <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">Newsletter</h3>

                    <p class="editContent">By subscribing to our mailing list you will always get latest news and
                        updates from us.</p>
                    <form action="#" method="post" class="w3layouts-newsletter">
                        <input type="email" name="Email" class="editContent" placeholder="Enter your email..."
                               required="">
                        <button class="btn1 btn"><span class="fa fa-paper-plane-o" aria-hidden="true"></span></button>

                    </form>
                </div>
                <div class="row mt-lg-4 bottom-w3layouts-sec-nav mx-0">
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">Разделы</h3>
                        <ul class="list-unstyled w3layouts-icons">
                            <li>
                                <a href="index.html" class="editContent">Главная</a>
                            </li>
                            <li>
                                <a href="about.html" class="editContent">Категории</a>
                            </li>
                            <li>
                                <a href="contact.html" class="editContent">Контакты</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <!-- social icons -->
                        <div class="agileinfo_social_icons">
                            <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">Pages</h3>
                            <ul class="list-unstyled w3layouts-icons">

                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                            </ul>
                        </div>
                        <!-- social icons -->
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts my-md-0 my-5">
                        <h3 class="footer-title text-uppercase text-wh mb-lg-4 mb-3 editContent">Contact Info</h3>
                        <div class="contact-info">
                            <div class="footer-address-inf my-4">
                                <h4 class="ad-info mb-2 editContent">Email </h4>
                                <p class="editContent"><a href="mailto:info@example.com">info@example.com</a></p>
                            </div>
                            <div class="footer-address-inf">
                                <h4 class="ad-info mb-2 editContent">Location</h4>
                                <p class="editContent">New York City</p>
                            </div>
                        </div>
                    </div>


                </div>

            </div>
        </div>
    </div>
</footer>
<!-- //footer -->
<div class="cpy-right py-3">
    <div class="container">
        <div class="row">
            <p class="col-md-10 text-left">© 2019 DjangoMovie. All rights reserved | Design by
                <a href="https://djangochannel.com"> DJANGO SCHOOL.</a>
            </p>
            <!-- move top icon -->
            <a href="#home" class="move-top text-right col-md-2"><span class="fa fa-long-arrow-up"
                                                                       aria-hidden="true"></span></a>
            <!-- //move top icon -->
        </div>
    </div>
</div>

movies/templates/include/header.html
{%load movie_tag%}
<header class="header">
    <div class="container-fluid px-lg-5">
        <!-- nav -->
        <nav class="py-4">
            <div id="logo">
                <h1><a href="index.html" class="editContent"
                       style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: &quot;Source Sans Pro&quot;, sans-serif;">DjangoMovie</a>
                </h1>
            </div>

            <label for="drop" class="toggle">Menu</label>
            <input type="checkbox" id="drop">
            <ul class="menu mt-2">
                <li class="active"><a href="#">Главная</a></li>
                <li>
                    <!-- First Tier Drop Down -->
                    <label for="drop-2" class="toggle">Категории <span class="fa fa-angle-down"
                                                                       aria-hidden="true"></span> </label>
                    <a href="#">Категории <span class="fa fa-angle-down" aria-hidden="true"></span></a>
                    <input type="checkbox" id="drop-2">
                    <ul>
                        {%get_categories as categories%}
                        {%for category in categories%}
                        <li><a href="#">{{category.name}}</a></li>
                        {%endfor%}
                    </ul>
                </li>
                <li><a href="contact.html"
                       style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Вход</a></li>
            </ul>
        </nav>
        <!-- //nav -->
    </div>
</header>
<!--/banner-->
<div class="banner-info">
    <p class="editContent">лучший сайт на django 3</p>
    <h3 class="mb-4 editContent">Все о кино</h3>
    <div class="ban-buttons">


    </div>
</div>
<!--// banner-inner -->

movies/templates/movies/actor.html
{% extends 'movies/base.html' %}
{% load static %}
{%block logo%}
<div class="main-banner bg " id="home">
    {%endblock logo%}
    {%block content%}

    <!---->
    <!-- banner -->

    <!-- //product left -->
    <!-- product right -->
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src={{actor.image.url}} class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{actor.name}}</h3>
                <ul>
                    <li style="list-style: none"><span><b>Год:</b> {{actor.age}}</span></li>
                    <li style="list-style: none">
                        <span><b>Режиссер:</b> {%for movie in actor.film_director.all%} <a
                                href="{{movie.get_absolute_url}}">{{movie}}</a> {%endfor%}</span>
                    </li>
                    <li style="list-style: none">
                    <span><b>Actor:</b> {%for movie in actor.film_actor.all%} <a
                            href="{{movie.get_absolute_url}}">{{movie}}</a>  {%endfor%}</span>
                    </li>


                                    </ul>
                                </div>
                            </div>
                            <div class="row sub-para-w3layouts mt-5">

                                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                                   About {{actor.name}}</h3>
                                <p>
                                    {{actor.description|safe}}
                                </p>
                            </div>
                            <hr>
                        </div>

                        {%endblock content%}
                    </div>

movies/templates/movies/base.html
{%extends 'base.html'%}

movies/templates/movies/moviesingle.html
{% extends 'movies/base.html' %}
{% load static %}
{%block logo%}
<div class="main-banner bg " id="home">
    {%endblock logo%}
    {%block content%}

    <!---->
    <!-- banner -->

    <!-- //product left -->
    <!-- product right -->
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src={{movie.poster.url}} class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{movie.title}}</h3>
                <h5 class="editContent">{{movie.title}}</h5>
                <ul>
                    <li style="list-style: none"><span><b>Год:</b> {{movie.year}}</span></li>
                    <li style="list-style: none"><span><b>Страна:</b> {{movie.country}}</span>
                    </li>
                    <li style="list-style: none"><span><b>Слоган:</b> «{{movie.tagline}}»</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Режиссер:</b> {%for director in movie.directors.all%} <a
                                href="{{director.get_absolute_url}}">{{director}}</a> {%endfor%}</span></li>
                    <li style="list-style: none"><span><b>Актеры:</b>{%for actor in movie.actors.all%} <a
                                href="{{actor.get_absolute_url}}">{{actor}}</a> {%endfor%}</span>
                    </li>
                    <li style="list-style: none"><span><b>Жанр:</b> {%for genre in movie.genres.all%} {{genre}} {%endfor%}</span>
                    </li>
                    <li style="list-style: none"><span><b>Премьера в мире:</b> {{movie.world_premier}}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Бюджет:</b> ${{movie.budget}}000</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в США:</b> ${{movie.fees_in_usa}}000</span></li>
                    <li style="list-style: none"><span><b>Сборы в мире:</b> ${{movie.fees_in_world}}000</span>
                    </li>
                    <li style="list-style: none">
                        <a href="#"><b>Рейтинг:</b>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="editContent"
                                  style="outline: none; cursor: inherit;">5.0</span>
                        </a>
                    </li>
                    <div class="share-desc">
                        <div class="share">
                            <h4 class="editContent"
                                style="outline: none; cursor: inherit;">
                                Share:</h4>
                            <ul class="w3layouts_social_list list-unstyled">
                                <li>
                                    <a href="#" class="w3pvt_facebook editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_twitter editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_dribble editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                О фильме Терминатор: Темные судьбы</h3>
            <p>
                {%for image in movie.movieshots_set.all %}
                <img src="{{image.image.url}}" class="img-shot" alt="{{image.description}}">
                {%endfor%}
            </p>
            <p class="editContent" style="outline: none; cursor: inherit;">Сара Коннор
                превратилась в настоящую охотницу
                за терминаторами и теперь занимается уничтожением роботов-убийц из
                будущего.
                Она считала, что главное — это не дать им добраться до Джона, но теперь
                появилась
                Дани Рамос, от выживания которой также зависит судьба человечества.
                Вместе с ней в бой вступает и загадочная Грейс, смесь человека и
                машины.</p>

            <p class="mt-3 editContent" style="outline: none; cursor: inherit;">
                Человечество дорого заплатило за технический прогресс, поставив под
                угрозу свое выживание.
                Пришло время покончить с войной между машинами и людьми.
                Научно-фантастический боевик,
                заключительная часть трилогии, перезапускающей франшизу «Терминатора»
                Джеймса Кэмерона.
            </p>
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;">02</span>Оставить отзыв</h3>
                    <form action="{%url 'add_review' movie.id%}" method="post" class="mt-4" id="formReview">
                        {%csrf_token%}
                        <input type="hidden" name='parent' id="contactparent" value="">
                        <div class="form-group editContent"
                             style="outline: none; cursor: inherit;">
                            <label for="contactcomment" class="editContent"
                                   style="outline: none; cursor: inherit;">Ваш комментарий
                                *</label>
                            <textarea class="form-control border" rows="5" name='text'
                                      id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent"
                                 style="outline: none; cursor: inherit;">
                                <label for="contactusername" class="editContent"
                                       style="outline: none; cursor: inherit;">Имя
                                    *</label>
                                <input type="text" class="form-control border" name='name'
                                       id="contactusername" required="">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent"
                                 style="outline: none; cursor: inherit;">
                                <label for="contactemail" class="editContent"
                                       style="outline: none; cursor: inherit;">Email
                                    *</label>
                                <input type="email" class="form-control border" name='email'
                                       id="contactemail" required="">
                            </div>
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3"
                                style="outline: none; cursor: inherit;">Отправить
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
            <div class="col-lg-8">
                {%for review in movie.get_review%}
                <div class="media py-5">
                    <img src="../../static/images/te2.jpg" class="mr-3 img-fluid" alt="image"
                         style="outline: none; cursor: inherit;">
                    <div class="media-body mt-4">
                        <h5 class="mt-0 editContent"
                            style="outline: none; cursor: inherit;">{{review.name}}</h5>
                        <p class="mt-2 editContent" style="outline: none; cursor: inherit;">
                            {{review.text}}
                        </p>
                        <a href="#formReview" onclick="addReview('{{review.name}}','{{review.id}}')">Reply</a>
                        {%for rew in review.reviews_set.all%}
                        <div class="media mt-5 editContent"
                             style="outline: none; cursor: inherit;">
                            <a class="pr-3" href="#">
                                <img src="../../static/images/te2.jpg" class="img-fluid "
                                     alt="image" style="outline: none; cursor: inherit;">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent"
                                    style="outline: none; cursor: inherit;">{{rew.name}}</h5>
                                <p class="mt-2 editContent"
                                   style="outline: none; cursor: inherit;"> {{rew.text}}</p>
                                <a href="#formReview" onclick="addReview('{{rew.name}}','{{review.id}}')">Reply</a>
                            </div>
                        </div>
                        {%endfor%}
                    </div>
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
    <script>
        function addReview(name, id) {
            // document.getElementById('contactcomment').autofocus=true;
            document.getElementById('contactparent').value = id;
            document.getElementById('contactcomment').innerText = `${name}, `;

            // document.getElementById('contactcomment').focus();




        }
    </script>
    {%endblock content%}
</div>